name: Peter Ellis, Stats in the Wild
highligher: pygments
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: I write about using real data for real purposes. I show how to access and use data, and provide examples of semi-finished products and the code that produced them. 'In the wild' is metaphorical - I don't write in particular about natural wilderness (although am happy to if the data comes up), as much as the rugged but human-made world of compromise, pragmatism, and difficult practical choices that is real-world data analysis. 
comments: true
gems:
  - jekyll-sitemap
url: http://ellisp.github.io
author: Peter Ellis


