name: Peter Ellis, stats in the wild
highligher: pygments
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
comments: true
url: "http://ellisp.github.io"
baseurl: "http://ellisp.github.io"
gems:
  - jekyll-sitemap



