name: Peter's stats stuff
highligher: pygments
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: I write about using data and analytical techniques like statistical modelling and simulation for real purposes. I show how to access and use data, and provide examples of analytical products and the code that produced them. 
comments: true
gems:
  - jekyll-sitemap
url: http://ellisp.github.io
author: Peter Ellis


