name: Peter's stats stuff
highligher: pygments
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: I write about applications of data and analytical techniques like statistical modelling and simulation to real-world situations. I show how to access and use data, and provide examples of analytical products and the code that produced them. 
comments: true
gems:
  - jekyll-sitemap
url: http://ellisp.github.io
author: Peter Ellis
fbauthor: https://www.facebook.com/peter.ellis.353

